### ISSUE TITLE
Fetching ads on iOS causes crashing.

### ISSUE THREAD

**Issue by raiyumi** [byrobingames/heyzap#3]
I've been testing on a ipod touch 6th gen and it seems like the game mostly crashes if I try to fetch from 'rewarded ads' or 'interstitial ads'. If it manages to fetch the ads(rewarded and interstitial) without crashing, then fetching those ads again works fine.. but that takes quite a bit of app restarting.

Fetching video ads seems like it has no crashing issues.

The ad networks I'm using with Heyzap is Unityads, Applovin, and admob.

**Comment by byrobingames** [comment]
Hi,

I have tested multi times on my iPhone 7 and game is not crashing. 
So I cannot replicate your issue.

Can you give me the crash logs from your device with Xcode. thanks..

**Comment by raiyumi** [comment]
[log-2019-04-02.zip](https://github.com/byrobingames/heyzap/files/3035760/log-2019-04-02.zip)
 Yep, here are some Stencyl crash logs. I'll try to get some Xcode crash logs in a bit.

**Comment by raiyumi** [comment]
[Boost Buddies_Final_v60u  4-1-19, 7-28 PM.txt](https://github.com/byrobingames/heyzap/files/3035976/Boost.Buddies_Final_v60u.4-1-19.7-28.PM.txt)

iOS crash logs on my touch 6.

**Comment by byrobingames** [comment]
Ok thanks, i see the game crash when fetching ad from Applovin, can you disable Applovin in Heyzap Dashboard en test it only with Unityads and Admob enabled.

Thanks...

**Comment by raiyumi** [comment]
Yes, it seems to work now. I've disabled the applovin extension and it doesn't crash while fetching.

**Comment by byrobingames** [comment]
Ok it seems that Heyzap does not support newest Applovin SDK that it is used in Applovin Extension yet, but it's a bit strange that it works on my side.

I try to check and fix some code tomorrow..

**Comment by raiyumi** [comment]
Sounds good. Probably has something to do with older devices.

**Comment by byrobingames** [comment]
Can you test this.. 
Heyzap support only Applovin SDK 5.1.2. (Applovin extension SDK is higher)

1) Download: https://s3.amazonaws.com/third-party-sdk/ios_applovin_5.1.2/applovin-ios-sdk-5.1.2.zip
2) Unzip it and Copy "**AppLovinSDK.framework**"
3) Go to /Users/HOME/stencylworks/engine-extensions/heyzap/frameworks and paste "**AppLovinSDK.framework**"
4) Now open /Users/HOME/stencylworks/engine-extensions/heyzap/include.xml and add <br/> **`<dependency path="frameworks/AppLovinSDK.framework"/>`** 
at line 21 

You now have this in the include.xml file.
```
<ndll name="heyzap" />
        
<dependency path="frameworks/HeyzapAds.framework"/>
<dependency path="frameworks/AppLovinSDK.framework"/>
<template path="templates" />
```
5) Now run clean project and build your game. (Applovin extension has to be disabled)
6) Check if the game is still crashing using this SDK version. If it is not crashing then this is the fix.

**Comment by raiyumi** [comment]
Modified and disabled the separate applovin extension.. seems like the problem still occurs.

**Comment by raiyumi** [comment]
For iOS heyzap.. for now I'm just using it with unityads and admob.

Another error I found that happens on android (after trying to put apk project in beta in the googleplay console), the pre-crash report says: ": 

(Only happens on their Moto Z test device)

> `Issue: java.lang.RuntimeException: Unable to destroy activity {com.raiyumi.boostbuddies/com.raiyumi.boostbuddies.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.heyzap.sdk.ads.BannerAdView.destroy()' on a null object reference`

```

> FATAL EXCEPTION: main
> Process: com.raiyumi.boostbuddies, PID: 11745
> java.lang.RuntimeException: Unable to destroy activity {com.raiyumi.boostbuddies/com.raiyumi.boostbuddies.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.heyzap.sdk.ads.BannerAdView.destroy()' on a null object reference
> 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4208)
> 	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4226)
> 	at android.app.ActivityThread.-wrap6(ActivityThread.java)
> 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1534)
> 	at android.os.Handler.dispatchMessage(Handler.java:102)
> 	at android.os.Looper.loop(Looper.java:154)
> 	at android.app.ActivityThread.main(ActivityThread.java:6123)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
> 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
> Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.heyzap.sdk.ads.BannerAdView.destroy()' on a null object reference
> 	at com.byrobin.heyzap.HeyzapEx.onDestroy(HeyzapEx.java:722)
> 	at org.haxe.lime.GameActivity.onDestroy(GameActivity.java:165)
> 	at android.app.Activity.performDestroy(Activity.java:6874)
> 	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1175)
> 	at androidx.test.runner.MonitoringInstrumentation.callActivityOnDestroy(MonitoringInstrumentation.java:167)
> 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4195)

```

**Comment by byrobingames** [comment]
Ok, thats cool...

For the Android issue:

1) Open file: _/Users/HOME/stencylworks/engineextensions/heyzap/dependencies/heyzap/src/com/byrobin/hezap/HeyzapEx.java_

2) Go to the bottom of the file and replace this: (line 720 to 723)

```
    @Override
    public void onDestroy() {
      super.onDestroy();
    }
```
With this code:
```
    @Override
    public void onDestroy() {
        if(banner != null){
             banner.destroy();
            }
      super.onDestroy();
    }

```

This should fix the issue, can you confirm this to me so I can make an update, thanks a lot for testing..

**Comment by raiyumi** [comment]
Thank you. I don't see it appearing as an error anymore.

I don't know why this is happening, but I've been getting "you must call heyzap ad.start first()" recently on android.

(Also I can continue testing applovin /w heyzap on iOS  if you want).

**Comment by byrobingames** [comment]
Ok i have made an update 2.9.3 for minor Android fix.

 "you must call heyzap ad.start first()" means the init block is not initialized properly.. So Heyzap is not set.

For iOS Applovin with heyzap there is nothing I can do, it is working on my devices iOS 12 >.

I am going to close this issue.. 
Thanks..
