### ISSUE TITLE
error on compiling

### ISSUE THREAD

**Issue by ChristianEG** [byrobingames/heyzap#4]
When i enable heyzap on the by robin extension (2.9.1) and try to test on my device it gives me this error:
[2019-04-18_11-01-47.log](https://github.com/byrobingames/heyzap/files/3095546/2019-04-18_11-01-47.log)

im using stencyl b 10321

**Comment by byrobingames** [comment]
You have to update Heyzap extension to version 2.9.3, you still have version 2.9.1 installed.

You can download  version 2.9.3 .zip file manually from https://github.com/byrobingames/heyzap/releases if update inside the Toolset is not working.

**Comment by ChristianEG** [comment]
Ok i will update manually thanks Robin.

Enviado desde mi iPod

El 18/04/2019, a las 1:27 p.m., Robin Schaafsma <notifications@github.com<mailto:notifications@github.com>> escribió:


You have to update Heyzap extension to version 2.9.3, you still have version 2.9.1 installed.

You can download version 2.9.3 .zip file manually from https://github.com/byrobingames/heyzap/releases if update inside Toolset not working.
