### ISSUE TITLE
Failed to build with Heyzap

### ISSUE THREAD

**Issue by ByteyBeasts** [byrobingames/heyzap#5]
Stencyl failed to test. Among others, it gave this:
`[haxelib] ignoring file /Users/guzboroda/stencylworks/engine-extensions/heyzap/frameworks/HeyzapAds.framework/HeyzapAds, file was built for unsupported file format ( 0x56 0x65 0x72 0x73 0x69 0x6F 0x6E 0x73 0x2F 0x41 0x2F 0x48 0x65 0x79 0x7A 0x61 ) which is not the architecture being linked (arm64): /Users/guzboroda/stencylworks/engine-extensions/heyzap/frameworks/HeyzapAds.framework/HeyzapAds`

I uploaded the log. Can you help me to figure out what went wrong?

[log-2019-11-14.zip](https://github.com/byrobingames/heyzap/files/3847494/log-2019-11-14.zip)

**Comment by byrobingames** [comment]
Read instruction on wiki

https://github.com/byrobingames/heyzap/wiki/4.-Error-on-Compiling

**Comment by ByteyBeasts** [comment]
Ok, now Stencyl compiles but the game crashes to desktop after Heyzap: Show Banner Ad.

**Comment by ByteyBeasts** [comment]
After I did what you said to me before, cleared project etc. Stencyl compiled. I sent the build to Apple and they rejected saying the game is crashing. Here are not symbolicated logs. I tried to exclude Heyzap and the game worked fine, so the problem in Heyzap. 
[attachment-158871824626635527crashlog-A175BF34-840C-47D6-9F24-B3D95A5DD40D.txt](https://github.com/byrobingames/heyzap/files/3853469/attachment-158871824626635527crashlog-A175BF34-840C-47D6-9F24-B3D95A5DD40D.txt)
[attachment-4931597359040411733crashlog-F1483DD7-CE4D-4B53-AFCE-F31CC55A7B00.txt](https://github.com/byrobingames/heyzap/files/3853470/attachment-4931597359040411733crashlog-F1483DD7-CE4D-4B53-AFCE-F31CC55A7B00.txt)
[attachment-15825197978123297433crashlog-0C3B9BD8-52E5-407C-9885-642DF3AE9273.txt](https://github.com/byrobingames/heyzap/files/3853471/attachment-15825197978123297433crashlog-0C3B9BD8-52E5-407C-9885-642DF3AE9273.txt)
[attachment-17774295792302867761crashlog-7EBEC676-F492-4E6A-9E0B-48E3B846AF77.txt](https://github.com/byrobingames/heyzap/files/3853472/attachment-17774295792302867761crashlog-7EBEC676-F492-4E6A-9E0B-48E3B846AF77.txt)

**Comment by ByteyBeasts** [comment]
In Console, I've managed to find this: 

> *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[HZBannerAd requestBannerWithOptions:delegate:success:failure:]: unrecognized selector sent to class 0x1061630e8'
> *** First throw call stack:
> (0x18201898c 0x181d410a4 0x181f20cc8 0x18201ce08 0x18201ebec 0x104a6fe94 0x104a71188 0x1056ea7d8 0x10525fe74 0x104ab5a08 0x104ab59a0 0x104f0b444 0x104f0c0ac 0x104f0c2f8 0x10521e74c 0x104f65410 0x104ec9538 0x104ed02d0 0x104ed077c 0x104acb414 0x1055e8674 0x1055e86d0 0x1056bc73c 0x1047856a0 0x1047c5380 0x18885e514 0x182f51eb0 0x181f6d6d4 0x181f96e5c 0x181f96588 0x181f9145c 0x181f908bc 0x18bdfc328 0x1860266d4 0x104a09678 0x181e1b460)

**Comment by byrobingames** [comment]
Ok thanks...

I see in that i dit not change the SDK download link in de Error wiki section, so if you did download SDK from that link then you have a old SDK version installed.(9.10.1)

Can you try to follow the Error wiki section again but instead download the SDK 9.10.1 try download version 9.56.0 from https://developers.heyzap.com/docs/ios_sdk_setup_and_requirements in the Download SDK section.

**Comment by ByteyBeasts** [comment]
Thanks for the update.
It seems now the game doesn't crash but I don't see banners while testing from Stencyl. From what I can see from Console Heyzap can not fill the banner and for some reason, block with Heyzap: Banner Ad did fail to load didn't catch the error. I tried to find some information about how to test ads with Heyzap but couldn't find it. Is it possible to test ads without uploading the game to TestFlight? 

![Screen Shot 2019-11-16 at 18 36 39](https://user-images.githubusercontent.com/57662709/68996871-2cf0f580-08a0-11ea-8a5d-f317bf675417.png)

Here is what Console shows me:

> default	17:20:28.295651 +0100	HeadlessD final	Heyzap SDK starting with options: 1, framework: (null), bundle ID: com.guzboroda.dungeon
> default	17:20:29.942749 +0100	HeadlessD final	
> 
> *** WARNING ***: Only one MoPub credential was found for the banner ad unit. Please add the credential for both phone and tablet on the dashboard
> default	17:20:37.296983 +0100	HeadlessD final	Call stack: (
> 	0   CoreFoundation                      0x00000001820189a0 DA838E75-6B30-360E-9661-C4800A7E1BF6 + 1227168
> 	1   libobjc.A.dylib                     0x0000000181d410a4 objc_exception_throw + 56
> 	2   CoreFoundation                      0x0000000181f20cc8 DA838E75-6B30-360E-9661-C4800A7E1BF6 + 212168
> 	3   CoreFoundation                      0x000000018201ce08 DA838E75-6B30-360E-9661-C4800A7E1BF6 + 1244680
> 	4   CoreFoundation                      0x000000018201ebec _CF_forwarding_prep_0 + 92
> 	5   HeadlessD final                     0x000000010544be7c -[HZFacebookAdapter internalInitializeSDK] + 252
> 	6   HeadlessD final                     0x00000001054338fc __30-[HZBaseAdapter initializeSDK]_block_invoke + 180
> 	7   HeadlessD final                     0x000000010538af8c hzEnsureMainQueue + 72
> 	8   HeadlessD final                     0x00000001054337e0 -[HZBaseAdapter initializeSDK] + 120
> 	9   HeadlessD final                     0x00000001053f9a68 __37-[HeyzapMediation setupAdapterNamed:]_block_invoke +
> default	17:27:56.393167 +0100	HeadlessD final	Heyzap SDK starting with options: 1, framework: (null), bundle ID: com.guzboroda.dungeon
> default	17:27:58.058367 +0100	HeadlessD final	
> 
> *** WARNING ***: Only one MoPub credential was found for the banner ad unit. Please add the credential for both phone and tablet on the dashboard
> default	17:28:03.703775 +0100	HeadlessD final	Call stack: (
> 	0   CoreFoundation                      0x00000001820189a0 DA838E75-6B30-360E-9661-C4800A7E1BF6 + 1227168
> 	1   libobjc.A.dylib                     0x0000000181d410a4 objc_exception_throw + 56
> 	2   CoreFoundation                      0x0000000181f20cc8 DA838E75-6B30-360E-9661-C4800A7E1BF6 + 212168
> 	3   CoreFoundation                      0x000000018201ce08 DA838E75-6B30-360E-9661-C4800A7E1BF6 + 1244680
> 	4   CoreFoundation                      0x000000018201ebec _CF_forwarding_prep_0 + 92
> 	5   HeadlessD final                     0x0000000103647e7c -[HZFacebookAdapter internalInitializeSDK] + 252
> 	6   HeadlessD final                     0x000000010362f8fc __30-[HZBaseAdapter initializeSDK]_block_invoke + 180
> 	7   HeadlessD final                     0x0000000103586f8c hzEnsureMainQueue + 72
> 	8   HeadlessD final                     0x000000010362f7e0 -[HZBaseAdapter initializeSDK] + 120
> 	9   HeadlessD final                     0x00000001035f5a68 __37-[HeyzapMediation setupAdapterNamed:]_block_invoke +
> default	18:30:09.905128 +0100	HeadlessD final	Heyzap SDK starting with options: 1, framework: (null), bundle ID: com.guzboroda.dungeon
> default	18:30:11.350192 +0100	HeadlessD final	
> 
> *** WARNING ***: Only one MoPub credential was found for the banner ad unit. Please add the credential for both phone and tablet on the dashboard
> default	18:30:18.776675 +0100	HeadlessD final	HZHeyzapExchangeBannerAdapter - requestFailedWithError: Error Domain=com.heyzap.ads.exchange.banners Code=1 "(null)" UserInfo={error=no_fill}
> default	18:30:19.615209 +0100	HeadlessD final	None of the available banner adapters were able to fetch an ad. Ad networks we checked: []. Retrying in 1 seconds...
> default	18:30:20.785541 +0100	HeadlessD final	HZHeyzapExchangeBannerAdapter - requestFailedWithError: Error Domain=com.heyzap.ads.exchange.banners Code=1 "(null)" UserInfo={error=no_fill}
> default	18:30:21.543268 +0100	HeadlessD final	None of the available banner adapters were able to fetch an ad. Ad networks we checked: []. Retrying in 2 seconds...
> default	18:30:23.656337 +0100	HeadlessD final	HZHeyzapExchangeBannerAdapter - requestFailedWithError: Error Domain=com.heyzap.ads.exchange.banners Code=1 "(null)" UserInfo={error=no_fill}
> default	18:30:24.473428 +0100	HeadlessD final	None of the available banner adapters were able to fetch an ad. Ad networks we checked: []. Retrying in 4 seconds...
> default	18:30:28.810679 +0100	HeadlessD final	HZHeyzapExchangeBannerAdapter - requestFailedWithError: Error Domain=com.heyzap.ads.exchange.banners Code=1 "(null)" UserInfo={error=no_fill}
> default	18:30:29.547816 +0100	HeadlessD final	None of the available banner adapters were able to fetch an ad. Ad networks we checked: []. Retrying in 8 seconds...
> default	18:30:38.691263 +0100	HeadlessD final	None of the available banner adapters were able to fetch an ad. Ad networks we checked: []. Retrying in 16 seconds...
> default	18:30:59.197795 +0100	HeadlessD final	HZHeyzapExchangeBannerAdapter - requestFailedWithError: Error Domain=com.heyzap.ads.exchange.banners Code=1 "(null)" UserInfo={error=no_fill}
> default	18:30:59.197817 +0100	HeadlessD final	HZHeyzapExchangeBannerAdapter - requestFailedWithError: Error Domain=com.heyzap.ads.exchange.banners Code=1 "(null)" UserInfo={error=no_fill}
> default	18:31:02.686145 +0100	HeadlessD final	HZHeyzapExchangeBannerAdapter - requestFailedWithError: Error Domain=com.heyzap.ads.exchange.banners Code=1 "(null)" UserInfo={error=no_fill}
> default	18:31:02.686018 +0100	HeadlessD final	HZHeyzapExchangeBannerAdapter - requestFailedWithError: Error Domain=com.heyzap.ads.exchange.banners Code=1 "(null)" UserInfo={error=no_fill}
> default	18:31:03.152267 +0100	HeadlessD final	None of the available banner adapters were able to fetch an ad. Ad networks we checked: []. Retrying in 1 seconds...
> default	18:31:03.152287 +0100	HeadlessD final	None of the available banner adapters were able to fetch an ad. Ad networks we checked: []. Retrying in 1 seconds...
> default	18:31:04.525123 +0100	HeadlessD final	HZHeyzapExchangeBannerAdapter - requestFailedWithError: Error Domain=com.heyzap.ads.exchange.banners Code=1 "(null)" UserInfo={error=no_fill}
> default	18:31:04.525141 +0100	HeadlessD final	HZHeyzapExchangeBannerAdapter - requestFailedWithError: Error Domain=com.heyzap.ads.exchange.banners Code=1 "(null)" UserInfo={error=no_fill}
> default	18:31:05.393313 +0100	HeadlessD final	None of the available banner adapters were able to fetch an ad. Ad networks we checked: []. Retrying in 2 seconds...
> default	18:31:05.393185 +0100	HeadlessD final	None of the available banner adapters were able to fetch an ad. Ad networks we checked: []. Retrying in 2 seconds...
> default	18:31:07.562462 +0100	HeadlessD final	HZHeyzapExchangeBannerAdapter - requestFailedWithError: Error Domain=com.heyzap.ads.exchange.banners Code=1 "(null)" UserInfo={error=no_fill}
> default	18:31:07.562409 +0100	HeadlessD final	HZHeyzapExchangeBannerAdapter - requestFailedWithError: Error Domain=com.heyzap.ads.exchange.banners Code=1 "(null)" UserInfo={error=no_fill}
> default	18:31:08.340536 +0100	HeadlessD final	None of the available banner adapters were able to fetch an ad. Ad networks we checked: []. Retrying in 4 seconds...
> default	18:31:08.340516 +0100	HeadlessD final	None of the available banner adapters were able to fetch an ad. Ad networks we checked: []. Retrying in 4 seconds...
> default	18:31:12.723441 +0100	HeadlessD final	HZHeyzapExchangeBannerAdapter - requestFailedWithError: Error Domain=com.heyzap.ads.exchange.banners Code=1 "(null)" UserInfo={error=no_fill}
> default	18:31:12.722938 +0100	HeadlessD final	HZHeyzapExchangeBannerAdapter - requestFailedWithError: Error Domain=com.heyzap.ads.exchange.banners Code=1 "(null)" UserInfo={error=no_fill}
> default	18:31:13.449276 +0100	HeadlessD final	None of the available banner adapters were able to fetch an ad. Ad networks we checked: []. Retrying in 8 seconds...
> default	18:31:13.449257 +0100	HeadlessD final	None of the available banner adapters were able to fetch an ad. Ad networks we checked: []. Retrying in 8 seconds...

**Comment by byrobingames** [comment]
I don’t know why the did fail block did not catch the error..

For testing Ads with heyzap use the Test SDK block under a button (only for debug)

https://github.com/byrobingames/heyzap/wiki/3.-Using-the-Heyzap-Extension#32-how-to-use-the-blocks

**Comment by ByteyBeasts** [comment]
Rewarded video crashed the game. I guess it's because Heyzap couldn't fetch the video (I saw it in console). Again the block didn't catch the error 
![Screen Shot 2019-11-16 at 20 04 07](https://user-images.githubusercontent.com/57662709/68997955-7f381380-08ac-11ea-83ae-c5271c263a95.png)

In debug mode it says all the networks I tried to set up on Heyzap website aren't available. Do I need to initialize UnityAds from your extensions in order to make it work in Heyzap? Because debug says 

> UnityAds SDK is not available 

Otherwise, I don't know how to make them available.

**Comment by byrobingames** [comment]
If you use Heyzap you must enable the ad network of your choice(Unity) in the Heyzap dashboard. 
Googles fist result: https://developers.heyzap.com/docs/-configuring-mediation

Heyzap only use the SDK from Unity extension, so you don’t have to use Unity initialize block or/and other blocks.

**Comment by byrobingames** [comment]
Also to receive test ads from Heyzap you have to fill in your Google Ad ID or 
iOS IDFA or IP address at the bottom on the Publisher settings page in Heyzap Dashboard.

**Comment by ByteyBeasts** [comment]
I've done all of these, for Facebook, Unity, Chartboost and MoPub. Some were easier to set up than others but all of them aren't available when I debug in my game. Even Unity which worked before when I used your separate extension. For Chartboost my game should be approved but before I need to do "initialize the SDK" via my game. I honestly don't know how to do this. Heyzap just shows that SDK is not available. Facebook, when I used your extension, showed me that the test is going well, but in Hezap it's again not available.

**Comment by ByteyBeasts** [comment]
I do use my iOs IDFA but it doesn't change anything. 
The funny thing is it keeps saying:

> *** WARNING ***: Only one MoPub credential was found for the incentivized ad unit. Please add the credential for both phone and tablet on the dashboard

But still doesn't show any banners. BTW there is no such thing on MoPub as ad unit specifically for tablets. Don't know how to deal with this also.

**Comment by ByteyBeasts** [comment]
I can't stop thinking about one thing. Do I need to keep the file "IASDKResources.bundle" inside the same folder as the file "HeyzapAds.framework" that I downloaded as you suggested? I'm asking because before that there was only one file "HeyzapAds.framework".

**Comment by byrobingames** [comment]
It is working on my side so I don't know what you doing wrong. All my enable networks on Heyzap dashboard are available in debug game.
It can take a while before it is enabled in debug.

No the IASDKResources.bundle needs copy to "/heyzap/templates/iPhone/PRJ/Classes"

The MoPub warning I don't now never used MoPub. MoPub is not support in Heyzap extension because SDK is not available, if you want to use MoPud you add the MoPud SDK manually.

**Comment by ByteyBeasts** [comment]
The only network marked by the green dot in debug mode is Heyzap and even from this network, it fails to show anything. In Console it says:

> HZHeyzapExchangeBannerAdapter - requestFailedWithError: Error Domain=com.heyzap.ads.exchange.banners Code=1 "(null)" UserInfo={error=no_fill}

Google doesn't give any hints of what this might be about.

**Comment by ByteyBeasts** [comment]
I'm not really sure how to read these stats from the Heyzap website, but I think it says that the connection is fine between the game and heyzap. Not sure though how I got 8 impressions on Unity when I haven't seen them and it's still not available. Could it be the reason in the extension? How to check if it's working?
![Screen Shot 2019-11-17 at 12 10 37](https://user-images.githubusercontent.com/57662709/69006737-d0d7b100-0933-11ea-802e-b204c144d581.jpg)

**Comment by byrobingames** [comment]
You can test it with the Test SDK block under a button (only for debug).

You have to click on the ad network that is green, then you can test it.
If it is not green make sure you have only enable the extension like unity to use the SDK.

**Comment by ByteyBeasts** [comment]
Here is what debug shows me. It's not visible here but Unity is also red. When I press on Heyzap Exchange, the only one that is green I press Show Banner, it then shows the error
![Heyzap Exchange](https://user-images.githubusercontent.com/57662709/69007252-d802bd00-093b-11ea-9fca-50ab149ffc33.PNG)

![IMG_49732](https://user-images.githubusercontent.com/57662709/69007224-704c7200-093b-11ea-8a33-6ea744c450b3.PNG)

**Comment by byrobingames** [comment]
ok then I don't know..

You use SDK 9.56.0 and I use SDK 9.54.1.

I try to update to 9.56.0 when I have the chance..

**Comment by ByteyBeasts** [comment]
Here is what it shows when I press Unity Ads
![Individual Net](https://user-images.githubusercontent.com/57662709/69007341-d980b500-093c-11ea-8fee-0584b9a418ad.PNG)

**Comment by byrobingames** [comment]
That’s indicates that you not have Unityads extension enabled..

**Comment by ByteyBeasts** [comment]
How do I enable the UnityAds extension? On Heyzap Website?

**Comment by byrobingames** [comment]
no in Stencyl go to the Toolset en enable unityads, like you did before when u used unity but now don’t use the Unity blocks..

**Comment by ByteyBeasts** [comment]
Thanks for the tip! Now I can see and test some networks. Facebook, however, crashes the game. In Console it says:

> *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[FBAdSettings bidderToken]: unrecognized selector sent to class 0x10253ff98'

Once I disabled Facebook SDK in Stencyl it went fine without crashes.

So, for now, I enabled AdMob, UnityAds, AppLovin, Vungle and all 3 Heyzap's options. Do I need to worry about some of these? Would they start to crash the game as Facebook does right now?

**Comment by byrobingames** [comment]
Facebook is not updated yet the others Will work..

**Comment by ByteyBeasts** [comment]
Just a few more questions. What is Tag for? In the Debug Mode when I test ads there is a Tag and sometimes it says that ad isn't available for the Tag Default. What is Tag?
When I upload the game to AppStore and test via TestFlight (meaning before making the build live) and with Anable Testing switched off in Stencyl and all the networks would I be able to see the ads on TestFlight?

**Comment by ByteyBeasts** [comment]
Since I enabled AppLovin and uploaded the game onto TestFlight Apple gave a warning. So, this might be interesting for you http://community.stencyl.com/index.php/topic,59429.0.html
