### ISSUE TITLE
Interstitial ad has a reward?

### ISSUE THREAD

**Issue by ByteyBeasts** [byrobingames/heyzap#6]
I'm implementing Interstitial Ads right now and while I was testing I've noticed there was an ad with the Close Button and when I pressed it it said: "you have to watch this video till the end to claim your reward". But I didn't plan to give any rewards! I wanted to annoy players so they would buy the "no ads" version of the game. It should be an ad between the scenes. This ad played like it was a Reward Video. Am I doing something wrong?

**Comment by byrobingames** [comment]
You can change publish setting in the Heyzap dashboard to change this.
