### ISSUE TITLE
Some networks aren't available on Android

### ISSUE THREAD

**Issue by ByteyBeasts** [byrobingames/heyzap#7]
I have separated setup on Heyzap website for Androids and iOs. On iOs it's working but on Android, it seems that Heyzap is working according to debug mode but some networks aren't available. The biggest problem is while banners aren't loaded, the rewarded video just crash the game (couldn't fetch?).
Applovin says "missing permission" and "network not enabled". I searched on Google and it seems that the "missing permission" issue has something to do with heyzap SDK (https://stackoverflow.com/questions/50132147/heyzap-integration-3rd-party-sdks-missing-permissions) while "network not enabled" issue I don't even know how to search. Can you help me with this?

See screenshots
![Screenshot_20191205-105143](https://user-images.githubusercontent.com/57662709/70224921-5c33ad80-174e-11ea-8f08-f5cc974b385b.png)
![Screenshot_20191205-105210](https://user-images.githubusercontent.com/57662709/70224922-5c33ad80-174e-11ea-9c1e-55d32349da68.png)
![Screenshot_20191205-105220](https://user-images.githubusercontent.com/57662709/70224924-5c33ad80-174e-11ea-937a-a634515dd097.png)

 attached

**Comment by byrobingames** [comment]
The permission part is indeed a Heyzap SDK issue, I don't have problems on my side.

The Network Not Enabled just means you do no have the Network enabled on Heyzap Dashboard in Android part. (Enable it just like on iOS part)
